services:
  billscanner-api:
    image: rutkre/billscanner-api:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8000
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.billscanner-api.rule=Host(`billscanner-api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.billscanner-api.entrypoints=websecure"
      - "traefik.http.routers.billscanner-api.tls=true"
      - "traefik.http.routers.billscanner-api.tls.certresolver=myresolver"
      # - "traefik.http.routers.billscanner-api.middlewares=chain-api-with-websocket@file"
      - "traefik.http.services.billscanner-api.loadbalancer.server.port=8000"
      # - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ${STACKS_VOLUME_PATH}/billscanner/appsettings.json:/app/appsettings.json
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "2"
        loki-max-backoff: "900ms"
        loki-timeout: "1s"
        keep-file: "true"
    networks:
      - postgres
      - proxy
      - redis
